name: Deploy

on:
  - push

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_HOST: "ssh://${{secrets.USER}}@${{secrets.HOST}}:${{secrets.PORT}}"
    steps:
      - uses: actions/checkout@v3
      - uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{secrets.PRIVATE_KEY}}

      - name: Disable Host key verification
        # Hack to prevent "Host key verification failed". Should be replaced with a ssh-keyscan based solution
        run: echo "StrictHostKeyChecking no" >> ~/.ssh/config

      - name: Check docker remote connection
        run: "docker version"

      - name: Pull caddy and start server
        run: "docker run -d -p 80:80 -p 443:443 --name caddy caddy:2"
        # Continue if caddy is running
        continue-on-error: true

      - name: Save Caddyfile for validation
        run: "docker exec -i caddy /bin/sh -c 'cat > /etc/caddy/Caddyfile_validate' < Caddyfile"

      - name: Validate Caddyfile
        run: "docker exec caddy caddy validate --config /etc/caddy/Caddyfile_validate"

      - name: Update configuration of running caddy
        run:  "docker exec -i caddy /bin/sh -c 'cat > /etc/caddy/Caddyfile' < Caddyfile"

      - name: Reload configuration of running caddy
        run: "docker exec caddy caddy reload --config /etc/caddy/Caddyfile"
        # Also fails if no config file is loaded
        continue-on-error: true